#### DA 2 Project
## Matching Users With Leetcode Problems
#### Piper Cush, Kailey Meyer, Nicolas Lopez

Github test 1

git add <nameof file changed> // I want to update these files <br>
git commit -m "YOURMESSAGE" // Changing the files and adding a description <br>
git push // actually making the changes <br>

To create a new branch: <br>
git checkout -b <nameofbranch> // creating a new branch <br>
git push origin <nameofbranch> // pushing to a branch <br>
git push --set-upstream origin <nameofbranch> // syncing the branch <br>

Branch commands: <br>
git checkout <nameofbranch> // switching to a branch <br>
git branch // checking which branch you are on <br>

In [12]:
import pandas as pd
#read csv
df = pd.read_csv('leetcode_dataset - lc.csv')
# organize the dataset based on acceptance rate
df = df.sort_values(by=['acceptance_rate'], ascending=False)
df.head()

,id,title,description,is_premium,difficulty,solution_link,acceptance_rate,frequency,url,discuss_count,accepted,submissions,companies,related_topics,likes,dislikes,rating,asked_by_faang,similar_questions
1756,1757,Recyclable and Low Fat Products,SQL Schema,1,Easy,NaN,95.6,7.8,https://leetcode.com/problems/recyclable-and-l...,26,6.2K,6.5K,Facebook,NaN,23,20,53,1,NaN
1264,1265,Print Immutable Linked List in Reverse,"You are given an immutable linked list, print ...",1,Medium,NaN,94.3,4.0,https://leetcode.com/problems/print-immutable-...,201,24K,25.4K,"Google,Facebook",NaN,266,54,83,1,NaN
1782,1783,Grand Slam Titles,SQL Schema,1,Medium,NaN,91.4,1.8,https://leetcode.com/problems/grand-slam-titles,64,1.9K,2.1K,Amazon,NaN,26,0,100,1,NaN
1569,1570,Dot Product of Two Sparse Vectors,"Given two sparse vectors, compute their dot pr...",1,Medium,/articles/dot-product-of-two-sparse-vectors,91.2,60.7,https://leetcode.com/problems/dot-product-of-t...,223,36.4K,39.9K,"Facebook,Apple","Array,Hash Table,Two Pointers",239,38,86,1,NaN
1740,1741,Find Total Time Spent by Each Employee,SQL Schema,1,Easy,NaN,91.2,1.5,https://leetcode.com/problems/find-total-time-...,48,5.1K,5.6K,Amazon,NaN,24,3,89,1,NaN

In [13]:
# shape of dataset
df.shape

(1825, 19)

In [14]:
df_selected = df[['title', 'description','acceptance_rate', 'difficulty', 'companies']]
df_selected.head()

,title,description,acceptance_rate,difficulty,companies
1756,Recyclable and Low Fat Products,SQL Schema,95.6,Easy,Facebook
1264,Print Immutable Linked List in Reverse,"You are given an immutable linked list, print ...",94.3,Medium,"Google,Facebook"
1782,Grand Slam Titles,SQL Schema,91.4,Medium,Amazon
1569,Dot Product of Two Sparse Vectors,"Given two sparse vectors, compute their dot pr...",91.2,Medium,"Facebook,Apple"
1740,Find Total Time Spent by Each Employee,SQL Schema,91.2,Easy,Amazon

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

#Define a TF-IDF Vectorizer Object. Remove all english stop words such as 'the', 'a'
tfidf = TfidfVectorizer(stop_words='english')

#Replace NaN with an empty string
df['overview'] = df['description'].fillna('')

#Construct the required TF-IDF matrix by fitting and transforming the data
tfidf_matrix = tfidf.fit_transform(df['description'])

#Output the shape of tfidf_matrix
tfidf_matrix.shape

(1825, 7218)

In [19]:
from sklearn.metrics.pairwise import linear_kernel

# Compute the cosine similarity matrix
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim.shape

(1825, 1825)

In [21]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices[:10]

title
Recyclable and Low Fat Products           1756
Print Immutable Linked List in Reverse    1264
Grand Slam Titles                         1782
Dot Product of Two Sparse Vectors         1569
Find Total Time Spent by Each Employee    1740
Capital Gain/Loss                         1392
Apples & Oranges                          1444
Invalid Tweets                            1682
Daily Leads and Partners                  1692
Rearrange Products Table                  1794
dtype: int64

In [22]:
def get_recommendations(title, cosine_sim=cosine_sim):
    # Get the index of the movie that matches the title
    idx = indices[title]

    # Get the pairwsie similarity scores of all movies with that movie
    sim_scores = list(enumerate(cosine_sim[idx]))

    # Sort the movies based on the similarity scores
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    # Get the scores of the 10 most similar movies
    sim_scores = sim_scores[1:11]

    # Get the movie indices
    movie_indices = [i[0] for i in sim_scores]

    # Return the top 10 most similar movies
    return df['title'].iloc[movie_indices]

In [23]:
get_recommendations('Grand Slam Titles')

1319    Minimum Distance to Type a Word Using Two Fingers
638                                        Decode Ways II
1736    Change Minimum Characters to Satisfy One of Th...
1404                                 Longest Happy String
388                                   Find the Difference
466                Unique Substrings in Wraparound String
1416                                  Reformat The String
393                                         Decode String
1543                                Make The String Great
679                                   Valid Palindrome II
Name: title, dtype: object